### ISSUE TITLE
Invalid regex in Windows machine

### ISSUE THREAD

**Issue by YarnSaw** [wesgarland/niim#19]
Tried running niim on windows 10 machine (my node version is 12 if that will effect it).
Immediately ran into an error:
```
There was an internal error in node-inspect. Please report this bug.
Invalid regular expression: /^~\/: \ at end of pattern
SyntaxError: Invalid regular expression: /^~\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at makeHistoryFilename (C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\niim.js:419:14)  
    at loadHistory (C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\niim.js:512:18)
    at Object.niim$$init [as init] (C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\niim.js:80:3)
    at C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\_inspect.js:107:14
    at new Promise (<anonymous>)
    at C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\_inspect.js:98:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\niim.js:419
    .replace(new RegExp('^~' + path.sep), os.homedir() + path.sep)
             ^

SyntaxError: Invalid regular expression: /^~\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at makeHistoryFilename (C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\niim.js:419:14)  
    at Object.nimm$recordHistory [as recordHistory] (C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\niim.js:438:18)
    at process.exitCleanup (C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\niim.js:88:11)   
    at process.emit (events.js:323:22)
    at process.EventEmitter.emit (domain.js:482:12)
    at process.exit (internal/process/per_thread.js:165:15)
    at process.handleUnexpectedError (C:\Users\ryant\AppData\Roaming\npm\node_modules\niim\lib\_inspect.js:399:13)
    at process.emit (events.js:323:22)
    at process.EventEmitter.emit (domain.js:482:12)
```

**Comment by wesgarland** [comment]
Fixed with version 1.12.1-a.  Thank you!
